def configure(ctx):
    print("Enigine configure")
    ctx.standard_defs()
    ctx.write_config_header('config.h')

def build(ctx):
    source_files = ['EngContainer.cpp',
                    'EngObserver.cpp',
                    'EngSubject.cpp',
                    'EngComponent.cpp',
                    'EngManager.cpp']
    ctx.shlib(
        target = 'enginelib',
        export_includes = '.',
        includes = '.',
        source = source_files,
        cflags = [ '-Wall', '-g' ],
        name = "intern_enginelib_sh"
    )
    ctx.stlib(
        target = 'enginelib',
        export_includes = '.',
        includes = '.',
        source = source_files,
        cflags = [ '-Wall', '-g' ],
        name = "intern_enginelib_st"
    )
